### ISSUE TITLE
Optimizing search/to_xarray for many filepaths in a collection

### ISSUE THREAD

**Issue by ahuang11** [intake/intake-esm#140]
So my collection holds about 5 million tiny files, each sized a couple hundred KBs.

This bloats the output collection catalog, making it a 4.7 GB netCDF file. So when I try to use `to_xarray()` after my query, it takes 2 minutes.

Any ideas/support for optimizing this? Thanks!

(Would a sqlite db be more suitable for collection catalogs?)

**Comment by ahuang11** [comment]
Under bld_collection_utils.py get_subset
```
    import datetime
    s = datetime.datetime.utcnow()
    ds = _open_collection(collection_name)
    e = datetime.datetime.utcnow()
    print(e - s)

    s = datetime.datetime.utcnow()
    collection_type = ds.attrs['collection_type']
    condition = np.ones(len(ds.index), dtype=bool)
    for key, val in query.items():
        if isinstance(val, list):
            condition_i = np.zeros(len(ds.index), dtype=bool)
            for val_i in val:
                condition_i = condition_i | (ds[key] == val_i)
            condition = condition & condition_i

        elif val is not None:
            condition = condition & (ds[key] == val)
    e = datetime.datetime.utcnow()
    print(e - s)

    s = datetime.datetime.utcnow()
    query_results = ds.where(condition, drop=True)
    e = datetime.datetime.utcnow()
    print(e - s)
```

0:00:00.036510
0:00:10.820615
MemoryError

**Comment by andersy005** [comment]
This is still something worth looking into. [DataFrame.query() Method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) might be a better alternative to the existing search method.

**Comment by andersy005** [comment]
With the refactor done in https://github.com/intake/intake-esm/pull/135, we don't use xarray/netCDF for catalogs anymore. So, I am going to close this for the time being. We can revisit it when there's a clear need for optimizing the existing search functionality.
