### ISSUE TITLE
Additional asset keywords in ESM collection JSON file

### ISSUE THREAD

**Issue by naomi-henderson** [intake/intake-esm#167]
I have been going through the hackathon notebooks and see quite a few folks **not** using `consolidated=True` in `open_esm_datastore` with the `pangeo-cmip6.json` file.  This particular catalog should always have this set, so it should really be specified in this JSON file.  

So, in particular, it would be great to be able to add a line to the `assets` section:
```
  "assets": {
    "column_name": "zstore",
    "format": "zarr",
    "consolidated": true
  },
```
and have the zarr_kwargs set accordingly. The default in `core.py` could still be false.

... and possibly one for `decode_times` since all of the datasets in this collection use the `cf_time` conventions.

This would be extremely useful as I convince other folks to use the fantastic new `to_dataset_dict`.  I am loving it, including the new pre-processing feature!

**Comment by andersy005** [comment]
@naomi-henderson, 

> and possibly one for decode_times since all of the datasets in this collection use the cf_time conventions.

For `decode_times` argument in [xr.open_zarr()](https://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html#xarray.open_zarr), the default value is `True`. 

How about updating the `zarr_kwargs` from `{}` --> `{"consolidated": True}` to be the default?

https://github.com/NCAR/intake-esm/blob/c3effddd9df0a55c61392941400c425267cff510/intake_esm/core.py#L235-L240

This appears to be the easiest fix with less amount of work compared to introducing the `consolidated` entry in the collection specification.

**Comment by naomi-henderson** [comment]
Of course many of the newer zarr collections tend to use consolidated=True, such as the GCS-CMIP6, but not all. If True was the default, then non-consolidated zarr collections with `intake-esm` might cause confusion.  Consolidated zarrs can be used with consolidated=False, but non-consolidated cannot be used with consolidated=True.  On the other hand, at least it would raise an error (no .zmetadata file found).

Do you think it is feasible to build an automatic check in `xr.open_zarr()` for the existence of .zmetadata ?  I don't know if this will degrade performance or break something else, so am hesitant to request this.

This is really a property of the collection itself and I still think it would be most appropriate in the specification, but understand that your time is a limited resource.  It is significantly slower if the user does not use consolidated=True when it is available.  This gives CMIP6 cloud users the impression that `to_dataset_dict` itself is too slow to use in a notebook.

**Comment by andersy005** [comment]
This has been addressed in xarray as part of 
- https://github.com/pydata/xarray/pull/5252
