### ISSUE TITLE
preprocess doesn't work with distributed

### ISSUE THREAD

**Issue by rabernat** [intake/intake-esm#228]
I think I have convinced myself that my preprocess function in `to_dataset_dict` does not run correctly when using a dask distributed client. This is a bit tricky to reproduce clearly. I'm sorry I don't have a complete example, but I thought I would make a quick note of it here, rather than forgetting about it.

**Comment by andersy005** [comment]
Do you have an example notebook I can use as a guide to diagnose the issue?
