### ISSUE TITLE
intake-esm-builder

### ISSUE THREAD

**Issue by fanchic** [intake/intake-esm#243]
Heya,

Here at the Bureau of Meteorology in Australia, we use intake-esm on CMIP5, CMIP6 and some regridded database.

Here is the version that we use :
intake-esm                2019.8.23.post3          pypi_0    pypi

To catalog the different database we use intake-esm-builder but that feature seemed to have disappeared in the recent versions of intake-esm and I am really struggling to see  how you build the catalogs in the new version.

What's the proper way of doing this now ?

Cheers,

Francois

**Comment by andersy005** [comment]
Hi @fanchic, 

As of intake-esm v2019.10 and later, intake-esm stopped building catalogs. We did this for two reasons:


- Once more people started using intake-esm for **different types** of Earth system archives beyond CMIP5 & CMIP6, it was obvious that building catalogs should be out of intake-esm's scope ( it is hard to have a general interface for building catalogs across all types of earth system data archives). 

- We created a specification ([esm-collection-spec](https://github.com/NCAR/esm-collection-spec/blob/master/collection-spec/collection-spec.md)) for intake-esm catalogs. All intake-esm catalogs must adhere to this specification. Here's an example of the [CMIP6 catalog](https://github.com/NCAR/intake-esm-datastore/blob/master/catalogs/glade-cmip6.json) in the new format. 


So, today if you want to use intake-esm, you need **two** files:

1. A JSON file: describes what the catalog (CSV file) contains, and how assets should be aggregated into xarray datasets

2. A CSV file: is the catalog itself. Contains comma separated values of assets and their corresponding metadata. 



a. Clone `intake-esm-datastore` repo:

```bash
git clone https://github.com/NCAR/intake-esm-datastore
cd intake-esm-datastore/builders
```

b. To build CMIP5 & CMIP6 catalogs (CSV files), follow the instruction available [here](https://github.com/NCAR/intake-esm-datastore/tree/master/builders) 


c. Once you have the CSV files created, you will need to create the JSON files. I recommend 
  - copying and pasting the contents of [glade-cmip6.json](https://github.com/NCAR/intake-esm-datastore/blob/master/catalogs/glade-cmip6.json) and [glade-cmip5.json](https://github.com/NCAR/intake-esm-datastore/blob/master/catalogs/glade-cmip5.json)
  - modifying ` "catalog_file": "glade-cmip6.csv.gz"` entry to point to csv files built in step (b.)

d. To use the built catalogs, you will need to point intake-esm to the new JSON files

```python
import intake
col = intake.open_esm_datastore(PATH_TO_JSON_FILE)
```

Let me know if you have any questions.

**Comment by fanchic** [comment]
Heya,

Thank you so much for your comprehensive email, everything is working like
a dream. We have catalogued CMIP6, CMIP5 datasets and also our regridded
products with intake-esm and it helped us doing some fantastic science.

Fantastic job Anderson.

Cheers,

Francois Delage

**Comment by andersy005** [comment]
Thank you for the kinds words and the update, @fanchic! So glad to hear that intake-esm is making it easier to do science :). Your feedback is highly appreciated!
