### ISSUE TITLE
Problem `'DummyProcess' object has no attribute 'terminate'` depending on dask scheduler 

### ISSUE THREAD

**Issue by jbusecke** [intake/intake-esm#254]
I am experiencing an issue like this periodically, when I am loading many datasets from a local catalog and also use preprocessing. 

```python
import intake
url = '/home/jbusecke/projects/cmip_data_management_princeton/catalogs/tigressdata-zarr-cmip6.json'
col = intake.open_esm_datastore(url)

from euc_dynamics.cmip6_preprocessing_stash import combined_preprocessing
cat = col.search(variable_id=['so'], source_id = models)
dd = cat.to_dataset_dict(zarr_kwargs={'consolidated':True, 'decode_times':False}, preprocess=combined_preprocessing)
```
results in `AttributeError: 'DummyProcess' object has no attribute 'terminate'` (full trace below). 

I am able to solve this by starting a dask.distributed `LocalCluster`, or using the `single-threaded` scheduler, pointing to the fact that this might be a problem with my preprocessing function and dask?

Sorry for this rather imprecise bug report, but I would be very grateful for any tips how to debug this.

<details>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    211         try:
--> 212             self._repopulate_pool()
    213         except Exception:

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/pool.py in _repopulate_pool(self)
    302     def _repopulate_pool(self):
--> 303         return self._repopulate_pool_static(self._ctx, self.Process,
    304                                             self._processes,

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/pool.py in _repopulate_pool_static(ctx, Process, processes, pool, inqueue, outqueue, initializer, initargs, maxtasksperchild, wrap_exception)
    325             w.daemon = True
--> 326             w.start()
    327             pool.append(w)

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/dummy/__init__.py in start(self)
     50             self._parent._children[self] = None
---> 51         threading.Thread.start(self)
     52 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/threading.py in start(self)
    851         try:
--> 852             _start_new_thread(self._bootstrap, ())
    853         except Exception:

RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-85ef214bc5f5> in <module>
----> 1 super_dict_time = master_load(variable_ids=['so'], require_all_on=None)#'o2', 'uo', 'vo', 'agessc'

/projects/GEOCLIM/LRGROUP/jbusecke/projects/euc_dynamics/euc_dynamics/utils.py in master_load(variable_ids, source_ids, experiment_ids, table_id, require_all_on, zarr, chunk, preprocess, drop_duplicate_grid_label, detrend_datasets, detrend_source_path, z_kwargs, c_kwargs)
    344         else:
    345             print("Reading %s for all models" % var)
--> 346             ddict = cat_var.to_dataset_dict(
    347                 zarr_kwargs=z_kwargs,
    348                 cdf_kwargs=c_kwargs,

~/code/intake-esm/intake_esm/core.py in to_dataset_dict(self, zarr_kwargs, cdf_kwargs, preprocess, storage_options, progressbar)
    628 
    629             for i, task in enumerate(concurrent.futures.as_completed(future_tasks)):
--> 630                 ds = task.result()
    631                 self._datasets[ds.attrs['intake_esm_dataset_key']] = ds
    632                 if self.progressbar:

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433 
    434             self._condition.wait(timeout)

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~/code/intake-esm/intake_esm/core.py in _load_source(source)
    616 
    617         def _load_source(source):
--> 618             return source.to_dask()
    619 
    620         sources = [source(**source_kwargs) for _, source in self.items()]

~/code/intake-esm/intake_esm/source.py in to_dask(self)
    120     def to_dask(self):
    121         """Return xarray object (which will have chunks)"""
--> 122         self._load_metadata()
    123         return self._ds
    124 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/intake/source/base.py in _load_metadata(self)
    124         """load metadata only if needed"""
    125         if self._schema is None:
--> 126             self._schema = self._get_schema()
    127             self.datashape = self._schema.datashape
    128             self.dtype = self._schema.dtype

~/code/intake-esm/intake_esm/source.py in _get_schema(self)
     83 
     84         if self._ds is None:
---> 85             self._open_dataset()
     86 
     87             metadata = {

~/code/intake-esm/intake_esm/source.py in _open_dataset(self)
    103             path: _path_to_mapper(path, self.storage_options) for path in self.df[self.path_column]
    104         }
--> 105         ds = _aggregate(
    106             self.aggregation_dict,
    107             self.aggregation_columns,

~/code/intake-esm/intake_esm/merge_util.py in _aggregate(aggregation_dict, agg_columns, n_agg, v, lookup, mapper_dict, zarr_kwargs, cdf_kwargs, preprocess)
    227         return ds
    228 
--> 229     return apply_aggregation(v)
    230 
    231 

~/code/intake-esm/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    179             agg_options = {}
    180 
--> 181         dsets = [
    182             apply_aggregation(value, agg_column, key=key, level=level + 1)
    183             for key, value in v.items()

~/code/intake-esm/intake_esm/merge_util.py in <listcomp>(.0)
    180 
    181         dsets = [
--> 182             apply_aggregation(value, agg_column, key=key, level=level + 1)
    183             for key, value in v.items()
    184         ]

~/code/intake-esm/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    179             agg_options = {}
    180 
--> 181         dsets = [
    182             apply_aggregation(value, agg_column, key=key, level=level + 1)
    183             for key, value in v.items()

~/code/intake-esm/intake_esm/merge_util.py in <listcomp>(.0)
    180 
    181         dsets = [
--> 182             apply_aggregation(value, agg_column, key=key, level=level + 1)
    183             for key, value in v.items()
    184         ]

~/code/intake-esm/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    160             # See https://github.com/NCAR/intake-esm/issues/172#issuecomment-549001751
    161             varname = lookup[v][0]
--> 162             ds = _open_asset(
    163                 mapper_dict[v],
    164                 data_format=data_format,

~/code/intake-esm/intake_esm/merge_util.py in _open_asset(path, data_format, zarr_kwargs, cdf_kwargs, preprocess, varname)
    266         return ds
    267     logger.debug(f'Applying pre-processing with {preprocess.__name__} function')
--> 268     return preprocess(ds)
    269 
    270 

/projects/GEOCLIM/LRGROUP/jbusecke/projects/euc_dynamics/euc_dynamics/cmip6_preprocessing_stash.py in combined_preprocessing(ds)
    233     if "yh" in ds.dims:
    234         ds = ds.rename({"yh": "y"})
--> 235     ds = cp(ds)
    236 
    237     if "time" in ds.dims:

~/code/cmip6_preprocessing/cmip6_preprocessing/preprocessing.py in combined_preprocessing(ds)
    410         ds = sort_vertex_order(ds)
    411         # convert vertex into bounds and vice versa, so both are available
--> 412         ds = maybe_convert_bounds_to_vertex(ds)
    413         ds = maybe_convert_vertex_to_bounds(ds)
    414 

~/code/cmip6_preprocessing/cmip6_preprocessing/preprocessing.py in maybe_convert_bounds_to_vertex(ds)
    302                 lat_b = xr.ones_like(ds.lon) * ds.coords["lat_bounds"]
    303 
--> 304                 lon_bb = xr.concat(
    305                     [lon_b.isel(bnds=ii).squeeze(drop=True) for ii in [0, 0, 1, 1]],
    306                     dim="vertex",

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/concat.py in concat(objs, dim, data_vars, coords, compat, positions, fill_value, join)
    133             "objects, got %s" % type(first_obj)
    134         )
--> 135     return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
    136 
    137 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/concat.py in _dataarray_concat(arrays, dim, data_vars, coords, compat, positions, fill_value, join)
    445         datasets.append(arr._to_temp_dataset())
    446 
--> 447     ds = _dataset_concat(
    448         datasets,
    449         dim,

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/concat.py in _dataset_concat(datasets, dim, data_vars, coords, compat, positions, fill_value, join)
    338 
    339     # determine which variables to concatentate
--> 340     concat_over, equals, concat_dim_lengths = _calc_concat_over(
    341         datasets, dim, dim_names, data_vars, coords, compat
    342     )

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/concat.py in _calc_concat_over(datasets, dim, dim_names, data_vars, coords, compat)
    272 
    273     process_subset_opt(data_vars, "data_vars")
--> 274     process_subset_opt(coords, "coords")
    275     return concat_over, equals, concat_dim_lengths
    276 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/concat.py in process_subset_opt(opt, subset)
    231                             # loads in order to avoid multiple loads from disk
    232                             # while keeping the RAM footprint low.
--> 233                             v_lhs = datasets[0].variables[k].load()
    234                             # We'll need to know later on if variables are equal.
    235                             computed = []

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/xarray/core/variable.py in load(self, **kwargs)
    366         """
    367         if isinstance(self._data, dask_array_type):
--> 368             self._data = as_compatible_data(self._data.compute(**kwargs))
    369         elif not hasattr(self._data, "__array_function__"):
    370             self._data = np.asarray(self._data)

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     70                 pool = pools[thread][num_workers]
     71             else:
---> 72                 pool = ThreadPool(num_workers)
     73                 atexit.register(pool.close)
     74                 pools[thread][num_workers] = pool

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/pool.py in __init__(self, processes, initializer, initargs)
    920 
    921     def __init__(self, processes=None, initializer=None, initargs=()):
--> 922         Pool.__init__(self, processes, initializer, initargs)
    923 
    924     def _setup_queues(self):

/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/multiprocessing/pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    214             for p in self._pool:
    215                 if p.exitcode is None:
--> 216                     p.terminate()
    217             for p in self._pool:
    218                 p.join()

AttributeError: 'DummyProcess' object has no attribute 'terminate'
</details>

**Comment by andersy005** [comment]
> I am able to solve this by starting a dask.distributed LocalCluster, or using the single-threaded scheduler, pointing to the fact that this might be a problem with my preprocessing function and dask?

I am curious. You mention that `distributed` and `single-threaded` schedulers work. What is the setup of your dask cluster that is failing?

**Comment by jbusecke** [comment]
Whatever is the default (I believe its `threaded`?).

**Comment by andersy005** [comment]
```python
/scratch/gpfs2/jbusecke/conda_tigressdata/envs/euc_dynamics/lib/python3.8/threading.py in start(self)
851 try:
--> 852 _start_new_thread(self._bootstrap, ())
853 except Exception:

RuntimeError: can't start new thread
```

This exception is suggesting that the problem may be that `max_workers` parameter passed to`ThreadPoolExecutor()` is higher than the threads allowed by your OS. 

What's the size of `len(cat.keys())`??


Internally, `intake-esm` loads datasets corresponding to keys in `cat.keys()` concurrently by launching a thread pool with `len(cat.keys())` threads. Additionaly, Dask is launching its own threads. So, It's likely that the total number of threads launched by both dask and intake-esm exceeds the total number allowed by your OS. 


Also, can you get the process ID of your notebook session or python script, and try watching its thread count:

```
watch ps -o thcount <pid>
```

**Comment by jbusecke** [comment]
That makes a lot of sense since I also checked to load each model separately, and the problem did not occur.

> What's the size of len(cat.keys())??

71

>  Also, can you get the process ID of your notebook session or python script, and try watching its thread count:

Seems to hover around 27-29 for now for the jupyter-lab process and around 3k !!! for the `python` process (which is the kernel?). 

When i set the scheduler to `single-threaded` the latter stays under 300.

**Comment by jbusecke** [comment]
Just FYI, I found [this](https://stackoverflow.com/questions/40621543/how-to-specify-the-number-of-threads-processes-for-the-default-dask-scheduler), and it seems to fix the problem for me.

**Comment by andersy005** [comment]
Thank you for the update! Should we close this?

**Comment by jbusecke** [comment]
Yup. This should be a good enough record for anyone else who might encounter the problem. Thanks for the swift help.
