### ISSUE TITLE
Move Intake-ESM to intake GitHub organization?

### ISSUE THREAD

**Issue by kmpaul** [intake/intake-esm#255]
Many other Intake plugins are moving to the Intake GitHub organization, such as Intake-STAC.  Is Intake-ESM ready to move?  Should it move?  If not, then why?

**Comment by andersy005** [comment]
> Is Intake-ESM ready to move?

I think so. No objection from me for moving it to intake organization provided @martindurant gives us the green light.

**Comment by martindurant** [comment]
Good from me. You can make me a member here and I can move it, or apparently any admin can initiate the move, and I should get a notification from the intake org.
Do you need more votes before kicking it off?

**Comment by kmpaul** [comment]
I think that's enough.  We can move it, as long as @andersy005 is on board.

**Comment by martindurant** [comment]
Done https://github.com/intake/intake-esm

**Comment by kmpaul** [comment]
woo-hoo!  We're here!
