### ISSUE TITLE
Recursion error issue when loading multiple models to dictionary

### ISSUE THREAD

**Issue by Recalculate** [intake/intake-esm#261]
Hi folks,

When using intake-esm on the new pangeo cloud to load numerous models to dictionary via ‘to_dataset_dict’ I’m encountering a recursion error, specifically:

RecursionError: maximum recursion depth exceeded while calling a Python object

From other posts in the forums this might be related to models with incompatible vertical coordinates (even though I’ve tried preprocessing prior to intake with the 'preprocess=' option). My question is, how can I tell which models/variable, out of potentially dozens, is causing the recursion error, if it is indeed the cause.

Code below:

```
import intake

col_url=‘https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json’
col = intake.open_esm_datastore(col_url)
col.aggregation_info[‘aggregations’][0].update({‘options’: {‘compat’: ‘override’}})

cat = col.search(require_all_on=[“source_id”],experiment_id=[‘ssp585’],table_id=‘Omon’,variable_id=[‘thetao’,‘so’,‘vmo’,‘dissic’],grid_label=‘gn’)

dset_dict_thetaso = cat.to_dataset_dict(zarr_kwargs={‘consolidated’: True, ‘decode_times’: True},cdf_kwargs={‘chunks’: {}, ‘decode_times’: True})

```

**Comment by dcherian** [comment]
This may be the upstream issue: https://github.com/pydata/xarray/issues/3666. What if you specified `use_cftime=True` in both `zarr_kwargs` and `cdf_kwargs`

**Comment by Recalculate** [comment]
Setting use_cftime=True in both zarr_kwargs and cdf_kwargs throws the error `open_zarr() got unexpected keyword arguments use_cftime`

The time issue seems to be the problem, as if we set the zarr_kwargs ‘decode_times’: False, then things run through.  It seems use_cftime hasn't been set for zarr?   In the interim, is there a way of identifying which models are causing the issue, so that I can explicitly exclude them?

**Comment by dcherian** [comment]
https://github.com/pydata/xarray/pull/3229

This PR looks close if someone wants to finish it up.

**Comment by andersy005** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the latest stable version(v2020.11.4)
