### ISSUE TITLE
Get the first member automatically

### ISSUE THREAD

**Issue by mickaellalande** [intake/intake-esm#266]
Some models don't have the member **r1i1p1f1** (for example **CNRM-CM6-1** that only have **r1i1p1f2**). So when we do a query like:

```python
col.search(
    experiment_id=["historical"],
    table_id="Amon",
    variable_id="tas",
    member_id="r1i1p1f1",
)
```

we miss all the models that don't have this first member. Would it be possible to implement an argument like for example `member_id="first"` that will automatically pick the first member available?

So far is it possible to do this by searching by hand what is the member for each model and finally request each model separately, but it would be great not to have to deal with that!

Thanks in advance to let me know if there is another solution and/or if this idea could be implemented in the future!

**Comment by andersy005** [comment]
@mickaellalande, 

You can use a wildcard or a regular expression for your search. Below I am using `"r1i1p1f*"` instead of `r1i1p1f1`. 


```python
In [14]: cat = col.search( 
    ...:     experiment_id=["historical"], 
    ...:     table_id="Amon", 
    ...:     variable_id="tas", 
    ...:     member_id="r1i1p1f*", 
    ...: )                                                                                      

In [15]: cat                                                                                    
Out[15]: <pangeo-cmip6 catalog with 51 dataset(s) from 56 asset(s)>

In [16]: cat.unique('member_id')                                                                
Out[16]: {'member_id': {'count': 3, 'values': ['r1i1p1f1', 'r1i1p1f2', 'r1i1p1f3']}}
```

Does this return what you expected?


P.S.:

For the wildcard search to work, you will need intake-esm v2020.08.15 (which hasn't been released yet) or later or you can use the master branch of intake-esm (`python -m pip install git+https://github.com/intake/intake-esm.git`)

**Comment by mickaellalande** [comment]
Great exciting feature! I guess it's already better to check the different indices of the realizations. Probably not exactly what I need, because I'd like to have only the first result from one model (for example `r1i1p1f1` for one model, `r2i1p1f1` or `r1i1p1f2` from another model if `r1i1p1f1` is not available, etc.).

**Comment by andersy005** [comment]
> because I'd like to have only the first result from one model (for example r1i1p1f1 for one model, r2i1p1f1 or r1i1p1f2 from another model if r1i1p1f1 is not available, etc.).

Here's what I'd try:

```python
In [40]: col
Out[40]: <pangeo-cmip6 catalog with 4201 dataset(s) from 282028 asset(s)>

In [41]: cat = col.search(experiment_id="historical", table_id="Amon", variable_id="tas")

In [42]: cat
Out[42]: <pangeo-cmip6 catalog with 53 dataset(s) from 532 asset(s)>

In [43]: grouped = cat.df.groupby(cat.groupby_attrs)

In [44]: cat.groupby_attrs
Out[44]:
['activity_id',
 'institution_id',
 'source_id',
 'experiment_id',
 'table_id',
 'grid_label']

In [45]: cat.df = grouped.first().reset_index()

In [46]: cat
Out[46]: <pangeo-cmip6 catalog with 53 dataset(s) from 53 asset(s)>

In [47]: cat.df.head()
Out[47]:
  activity_id institution_id  ... dcpp_init_year   version
0        CMIP        AS-RCEC  ...            NaN  20200218
1        CMIP            AWI  ...            NaN  20191015
2        CMIP            AWI  ...            NaN  20200212
3        CMIP            BCC  ...            NaN  20181126
4        CMIP            BCC  ...            NaN  20181214

[5 rows x 11 columns]
```

Let me know if this gives you what you want.

**Comment by mickaellalande** [comment]
Yes, that's great thank you, it is exactly what I needed!

**Comment by andersy005** [comment]
Awesome! Closing this for now. Feel free to reopen if you run into a similar issue.

**Comment by huazai-beyond121** [comment]
Thanks very much！still a problem a bit. As the subject said, when I choose `r1i1p1f1`, if some models have multiple integrated  'r', such as `r10i1p1f1` and `r1i1p1f1`, according to this, r10i1p1fi will be selected by default, and `r1i1p1f1` will be ignored (even if it exists)；In this case,  can `r1i1p1f1`  only be selected  manually on the basis of the previous？
