### ISSUE TITLE
How do you make these awesome release notes?

### ISSUE THREAD

**Issue by jbusecke** [intake/intake-esm#317]
I love the [intake-esm release notes](https://github.com/intake/intake-esm/releases). Are these generated automatically somehow? Or is that all manual?

**Comment by andersy005** [comment]
I use this package: https://github-activity.readthedocs.io/en/latest/. If you have a compatible [PR labeling system](https://github-activity.readthedocs.io/en/latest/#splitting-prs-by-tags-and-prefixes), github-activity may be able to do 95% of the work. The remaining 5% (adjusting titles or adding emojis) can be done manually.

**Comment by jbusecke** [comment]
Ohhh awesome. Ill def take a look!
