### ISSUE TITLE
Confusion about 'official' catalog for pangeo cmip6

### ISSUE THREAD

**Issue by jbusecke** [intake/intake-esm#323]
We had some issues over at [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing/issues/93#issuecomment-781264590) where users followed the intake-esm docs to load the pangeo cmip6 data. 

If I understand correctly, the main catalog file to use is now `"https://storage.googleapis.com/cmip6/pangeo-cmip6.json"`, should we change the docs accordingly? 

Or is there a specific reason to use the NCAR version?

cc @naomi-henderson

**Comment by andersy005** [comment]
> Or is there a specific reason to use the NCAR version? 

Nope. The NCAR version is a legacy version that existed before there was an official catalog for pangeo-cmip6. I kept maintaining it, but I think it may be a good time to deprecate it so as to avoid any confustion.

**Comment by andersy005** [comment]
This has been addressed in the documentation
