### ISSUE TITLE
Selecting monthly data from CMIP6 data 

### ISSUE THREAD

**Issue by jdldeauna** [intake/intake-esm#327]
Hello! I've been using intake-esm to download CMIP6 data, and I've been getting the following error when I try to select data from specific months ([sample notebook](https://github.com/jdldeauna/GitHub-Issues/blob/master/Select%20specific%20months%20from%20CMIP6%20data.ipynb)):

```
TypeError: '.dt' accessor only available for DataArray with datetime64 timedelta64 dtype or for arrays containing cftime datetime objects.
```

I tried using pandas to download data and was able to select specific months from that data. I wonder if I'm using intake-esm correctly, or if there's a more effective way to subset. Thank you!

**Comment by andersy005** [comment]
@jdldeauna, 

This code snippet is the culprit: 

```python
cmip6_compiled = cat.to_dataset_dict(
            zarr_kwargs={'consolidated':True, 'decode_times':False},
            preprocess=combined_preprocessing
            )
```

Notice the `decode_times: False` which tells xarray _not to convert_ time values from floats to datetime compatible objects. 


The following should fix the issue: 

```python
cmip6_compiled = cat.to_dataset_dict(
            zarr_kwargs={'consolidated':True, 'decode_times': True, 'use_cftime': True},
            preprocess=combined_preprocessing
            )
```

Let me know if this solution works for your use case.

**Comment by jdldeauna** [comment]
I see, thank you so much! It worked for me. I apologize for the oversight.

**Comment by andersy005** [comment]
> I see, thank you so much! It worked for me. I apologize for the oversight.

Of course! No apology necessary. We just need better documentation -:)
