### ISSUE TITLE
Ensure coordinate dimensions are sorted

### ISSUE THREAD

**Issue by andersy005** [intake/intake-esm#343]
Currently, we create or modify coordinate dimensions via `join_existing` and `join_new` without ensuring that the resulting coordinate labels are sorted. This results in datasets with time coordinates that are not monotonically increasing leading to issues when using features like `.sel()`. We should make sure that the dimensions are sorted before returning the dataset.

**Comment by dcherian** [comment]
Are you calling not calling `sorted` on a `glob.glob` call somewhere?

**Comment by andersy005** [comment]
> Are you not calling `sorted` on a `glob.glob` call somewhere?

Nope... we use whatever order the files appear in the catalog. I used to deal with this issue by properly sorting files while building the catalogs.

**Comment by andersy005** [comment]
This is now being taken care of here:

https://github.com/intake/intake-esm/blob/7143af48c67e347ae74db1305b0a0ce481fc9587/intake_esm/source.py#L230-L236

This ensures that the datasets are sorted before applying the aggregations.
