### ISSUE TITLE
Add functionality to dictionary output by .to_dataset_dict()

### ISSUE THREAD

**Issue by mgrover1** [intake/intake-esm#352]
Create a custom dict like object, which has the following additional methods:
- map - maps functions to all datasets in dictionary
  - If you don't specify the keys, apply to everything
  - if given keys, apply to certain keys

Additional attributes
- query that produced datasets
- original catalog

**Comment by andersy005** [comment]
This has been implemented in https://github.com/NCAR/xcollection and https://github.com/intake/intake-esm/pull/405
