### ISSUE TITLE
Overview chapter in User Guide fails to build (unique takes no arguments)

### ISSUE THREAD

**Issue by d70-t** [intake/intake-esm#404]
The [overview](https://intake-esm.readthedocs.io/en/latest/user-guide/overview.html#finding-unique-entries-for-individual-columns) page in the latest user guide fails with a `TypeError`.
The same error happens in the [CMIP6 tutorial](https://intake-esm.readthedocs.io/en/latest/user-guide/cmip6-tutorial.html#finding-unique-entries)

The `unique` function seemingly doesn't accept any parameters. I don't know if this is a bug in the code or in the docs.

**Comment by andersy005** [comment]
Thank you for looking into this! 

This is a bug in the docs. The API changed and the docs need to be updated to reflect this.
