### ISSUE TITLE
Allow subclassing `esm_datastore`

### ISSUE THREAD

**Issue by aulemahal** [intake/intake-esm#415]
**Is your feature request related to a problem? Please describe.**
In the workflow I am building, which takes the form a package, I want to extend the `esm_datastore` class with some quite specific functionalities. Mostly things that don't really make sense in `intake_esm` directly. However, when subclassing `esm_datastore`, a call to  `search` returns a `esm_datastore` object because the class is explicitly initialized.

**Describe the solution you'd like**
Replacing: 
https://github.com/intake/intake-esm/blob/e24e39ced1128f1b7cbc1edf9d467b1b8e301940/intake_esm/core.py#L347
with:
```python3
        cat = self.__class__({'esmcat': self.esmcat.dict(), 'df': esmcat_results})
```

**Describe alternatives you've considered**
A complicated override of `search` on my subclass. Since the introduction of the derived variable registry, this has been complicated and it's not only a matter of reconstructing a new object with the new `df`.

**Comment by andersy005** [comment]
> A complicated override of search on my subclass. Since the introduction of the derived variable registry, this has been complicated and it's not only a matter of reconstructing a new object with the new df.

Sorry to hear about this complication introduced by the `DerivedVariable` registry functionality... The `DerivedVariable` registry functionality is a little finicky/fragile for the time being. So, I think your proposed change is reasonable and would welcome a PR.

**Comment by aulemahal** [comment]
I really like the `DerivedVariable` feature, so I didn't mean this as a critic! The complexity it introduces simply justifies the suggested change. PR coming real soon.
