### ISSUE TITLE
Option to write uncompressed catalogs

### ISSUE THREAD

**Issue by aulemahal** [intake/intake-esm#419]
**Is your feature request related to a problem? Please describe.**
The default csv file written by `cat.serialize` is compressed with `gzip`. This is quite cool for large catalogs, but it looses some interoperability with low-level editing tools (text editors) as it's now a binary file.

**Describe the solution you'd like**
An option to control the compression of the catalog file. It could even be interesting for some to control the _codec_ used? Like a `compression` argument, the same as `pd.read_csv`, but without the "infer" option, since the catalog filename is not passed explicitly. So one of `{ ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}`.

**Describe alternatives you've considered**
Serializing the catalog myself with `cat.df.to_csv`, but that's just not ideal.

**Comment by aulemahal** [comment]
EDIT: In face, there could simply be a `**csv_kwargs` passed directly to `df.to_csv`? 
I am ok with changing the default value of `compression` and injecting `index=False`, I just think it could be interesting to have finer control.

**Comment by andersy005** [comment]
> EDIT: In fact, there could simply be a **csv_kwargs passed directly to df.to_csv?
>  I just think it could be interesting to have finer control.

👍🏽 

How about adding a `to_csv_kwargs` argument to 

https://github.com/intake/intake-esm/blob/40fe3a7808c14af77d96cfc932b9cebaa6beba10/intake_esm/core.py#L362-L367


and passing these keyword arguments down to 

https://github.com/intake/intake-esm/blob/40fe3a7808c14af77d96cfc932b9cebaa6beba10/intake_esm/cat.py#L118

?
