### ISSUE TITLE
Change `cat.serialize()` description

### ISSUE THREAD

**Issue by jukent** [intake/intake-esm#465]
Currently the `catalog.serialize()` method sets the description as "This is an ESM collection ... ", when "This is a ESM catalog ..." would be more appropriate.

Not sure yet if this is a fix here or upstream on `intake`. I don't see where it would be changed in https://github.com/intake/intake-esm/blob/a5c6ef02e217bf9fecca7efbf0139fe9f726d14d/intake_esm/core.py#L377

**Comment by andersy005** [comment]
https://github.com/intake/intake-esm/blob/5d26293bce2d4981fa9cf130742d1530c6c3cb0b/intake_esm/cat.py#L124 is another relevant method. This is where the actual serialization happens.

**Comment by andersy005** [comment]
> Currently the catalog.serialize() method sets the description as "This is an ESM collection ... ",

I think this is being copied from the parent catalog. The existing code doesn;t modify the `description` JSON field (I believe).

**Comment by jukent** [comment]
The description is most likely a legacy issue and not a coding one. My workflow was subsetting a catalog and then serializing that catalog -- and this description is probably copied from the original catalog. So maybe I should edit the text in the original catalogs or ignore.

**Comment by jukent** [comment]
###
