### ISSUE TITLE
broken example in documentation

### ISSUE THREAD

**Issue by dcherian** [intake/intake-esm#481]
The last cell here is raising an error: https://intake-esm.readthedocs.io/en/stable/user-guide/search.html#enforce-query-criteria-via-require-all-on-argument

**Comment by mgrover1** [comment]
@dcherian @andersy005 this appears to be resolved in the updated example

https://intake-esm.readthedocs.io/en/latest/how-to/enforce-search-query-criteria-via-require-all-on.html
