### ISSUE TITLE
cmip6 tutorial to_dataset_dict doesn't work for AWS s3

### ISSUE THREAD

**Issue by ollie-bell** [intake/intake-esm#495]
When running the cmip6 tutorial (https://intake-esm.readthedocs.io/en/stable/user-guide/cmip6-tutorial.html) replacing `url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"` with `url = "https://cmip6-pds.s3.amazonaws.com/pangeo-cmip6.json"`, the call to `to_dataset_dict` fails with the following error message:

```
Failed to open zarr store.

            *** Arguments passed to xarray.open_zarr() ***:

            - store: <fsspec.mapping.FSMap object at 0x0000024A29E0B160>
            - kwargs: {'consolidated': True, 'decode_times': True, 'use_cftime': True}
 
            *** fsspec options used ***:

            - root: cmip6-pds/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r2i1p1f1/Oyr/o2/gn/v20191121
            - protocol: ('s3', 's3a')

            ********************************************
```

output of `intake_esm.show_versions()`:

```
INSTALLED VERSIONS
------------------

cftime: 1.6.1
dask: 2022.7.0
fastprogress: 1.0.2
fsspec: 2022.5.0
gcsfs: 2022.5.0
intake: 0.6.5
intake_esm: 2021.8.17
netCDF4: 1.6.0
pandas: 1.4.3
requests: 2.28.1
s3fs: 2022.5.0
xarray: 2022.3.0
zarr: 2.12.0
```

**Comment by ollie-bell** [comment]
possibly related to #301 ?

**Comment by andersy005** [comment]
@ollie-bell, i believe the issue may have to do with credentials. when you get a chance, can you try the following 


```python
dsets = cat_sub.to_dataset_dict(xarray_open_kwargs=dict(backend_kwargs={'storage_options': {'anon': True}}))
```

This assumes you are using the main branch of intake-esm.

**Comment by andersy005** [comment]
i'm noticing some weird behavior in the resulting dataset. The `dcpp_init_year` dimension has a `nan` value which I think should not be there (most likely a bug in intake-esm). 

```python
In [19]: dsets = cat_sub.to_dataset_dict(xarray_open_kwargs=dict(backend_kwargs={'storage_options': {'anon': True}}))

--> The keys in the returned dictionary of datasets are constructed as follows:
        'activity_id.institution_id.source_id.experiment_id.table_id.grid_label'
 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.00% [1/1 00:41<00:00]
In [20]: dsets
Out[20]: 
{'CMIP.EC-Earth-Consortium.EC-Earth3-CC.historical.Oyr.gn': <xarray.Dataset>
 Dimensions:             (member_id: 1, dcpp_init_year: 1, time: 165, lev: 75,
                          j: 292, i: 362, bnds: 2, vertices: 4)
 Coordinates:
   * i                   (i) int32 1 2 3 4 5 6 7 ... 356 357 358 359 360 361 362
   * j                   (j) int32 1 2 3 4 5 6 7 ... 286 287 288 289 290 291 292
     latitude            (j, i) float64 dask.array<chunksize=(292, 362), meta=np.ndarray>
   * lev                 (lev) float64 0.5058 1.556 2.668 ... 5.698e+03 5.902e+03
     lev_bnds            (lev, bnds) float64 dask.array<chunksize=(75, 2), meta=np.ndarray>
     longitude           (j, i) float64 dask.array<chunksize=(292, 362), meta=np.ndarray>
   * time                (time) datetime64[ns] 1850-07-02T12:00:00 ... 2014-07...
     time_bnds           (time, bnds) datetime64[ns] dask.array<chunksize=(165, 2), meta=np.ndarray>
     vertices_latitude   (j, i, vertices) float64 dask.array<chunksize=(292, 362, 4), meta=np.ndarray>
     vertices_longitude  (j, i, vertices) float64 dask.array<chunksize=(292, 362, 4), meta=np.ndarray>
   * member_id           (member_id) <U8 'r1i1p1f1'
   * dcpp_init_year      (dcpp_init_year) float64 nan
 Dimensions without coordinates: bnds, vertices
 Data variables: (12/25)
     cfc11               (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 21, 75, 292, 362), meta=np.ndarray>
     cfc12               (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 21, 75, 292, 362), meta=np.ndarray>
     chl                 (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     detoc               (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     dfe                 (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     dissic              (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     ...                  ...
     remoc               (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     sf6                 (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 21, 75, 292, 362), meta=np.ndarray>
     si                  (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     talk                (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     zmeso               (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
     zmicro              (member_id, dcpp_init_year, time, lev, j, i) float32 dask.array<chunksize=(1, 1, 3, 75, 292, 362), meta=np.ndarray>
 Attributes: (12/53)
     Conventions:                        CF-1.7 CMIP-6.2
     activity_id:                        CMIP
     branch_method:                      standard
     branch_time_in_child:               0.0
     branch_time_in_parent:              0.0
     cmor_version:                       3.5.0
     ...                                 ...
     intake_esm_attrs/table_id:          Oyr
     intake_esm_attrs/grid_label:        gn
     intake_esm_attrs/dcpp_init_year:    nan
     intake_esm_attrs/version:           20210113
     intake_esm_attrs/_data_format_:     zarr
     intake_esm_dataset_key:             CMIP.EC-Earth-Consortium.EC-Earth3-CC...}
```

**Comment by ollie-bell** [comment]
Thanks @andersy005 that suggestion did help. The tutorial works now when using s3 instead of gcs.

However, I am intermittently running in to issues using a different catalogue. The dataset download seems to get stuck on a specific zstore (see attached image). 

Any ideas how to diagnose what the problem might be with this specific zstore? The [actual store in gcs does exist](https://console.cloud.google.com/storage/browser/cmip6/CMIP6/ScenarioMIP/NCAR/CESM2-WACCM/ssp585/r1i1p1f1/Amon/tas/gn/v20200702;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false), not sure why it would fail to download.

![image](https://user-images.githubusercontent.com/56110893/182937686-207336a7-ece5-453d-9e8f-9e2e56a44f45.png)

**Comment by andersy005** [comment]
> However, I am intermittently running in to issues using a different catalogue. The dataset loading seems to get stuck on a specific zstore (this time from gcs - see attached image)


how are you calling `.to_dataset_dict()`? 

for gcs, you should be using `token: 'anon'`, I believe 

```python
dsets = cat_sub.to_dataset_dict(xarray_open_kwargs=dict(backend_kwargs={'storage_options': {'token': 'anon'}}))
```

**Comment by andersy005** [comment]
by the way, thank you for your patience and for reporting this issue. It's been a while since our last release of intake-esm, and it's nice to have these bug/enhancement reports as we prepare to cut a new release.

**Comment by ollie-bell** [comment]
@andersy005 yes I have used it with `"token": "anon"`... but still having issues when trying to load datasets at a larger scale than in the tutorial.

For example, following https://intake-esm.readthedocs.io/en/latest/tutorials/index.html but replacing `url = intake_esm.tutorial.get_url('google_cmip6')` with `url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"` and also removing `table_id="Oyr"` from the search so that I end up with `cat_subset` containing 56 datasets. 

In this case, for me, the dataset loading either takes a very long time (10+ minutes before I halt) without completing or it errors as I showed in my previous comment after some `dask.array.core.PerformanceWarning` messages about chunk sizes start to appear. I'm finding it pretty difficult to diagnose what the problem is. 

If you follow the steps I described above to modify the tutorial do you run in to similar issues?

**Comment by ollie-bell** [comment]
@andersy005 Not to worry, pretty sure I have figured my issue... I think it's related to the ESM Catalog aggregations just not being suitable for every dataset I'm trying to load.

I'll close this now as the original issue was diagnosed as me not using `storage_options` in `backend_kwargs` correctly. Below is an explanation of what I think the remaining problem I was having is for anyone else who may find it useful.

-------------------------------------------------------------------------------------------------------------------------------------

Below is a snippet from https://cmip6-pds.s3.amazonaws.com/pangeo-cmip6.json ... the aggregations are forcing a join on `member_id`, but I suspect that sometimes the shapes of the individual datasets just aren't compatible with such a join. The exception gets thrown during the call to [`xr.combine_by_coords`](https://github.com/intake/intake-esm/blob/bc54ed5dca9088be48bb7801e21aedb39c5d342e/intake_esm/source.py#L255).

e.g. my explanation is that the datasets below will fail to join on `member_id` because `r3i1p1f1` has a time dimension of 61494 `r1i1p1f1` & `r2i1p1f1` have a time dimension of 60225.

s3://cmip6-pds/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/day/tas/gn/v20191108/
s3://cmip6-pds/CMIP6/CMIP/NCC/NorESM2-MM/historical/r2i1p1f1/day/tas/gn/v20200218/
s3://cmip6-pds/CMIP6/CMIP/NCC/NorESM2-MM/historical/r3i1p1f1/day/tas/gn/v20200702/

```json
"aggregation_control": {
    "variable_column_name": "variable_id",
    "groupby_attrs": [
      "activity_id",
      "institution_id",
      "source_id",
      "experiment_id",
      "table_id",
      "grid_label"
    ],
    "aggregations": [
      {
        "type": "union",
        "attribute_name": "variable_id"
      },

      {
        "type": "join_new",
        "attribute_name": "member_id",
        "options": { "coords": "minimal", "compat": "override" }
      },
      {
        "type": "join_new",
        "attribute_name": "dcpp_init_year",
        "options": { "coords": "minimal", "compat": "override" }
      }
    ]
  }
```
