### ISSUE TITLE
To Dataset Dict failing with CESM2-LE Example

### ISSUE THREAD

**Issue by mgrover1** [intake/intake-esm#506]
Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] Output of `intake_esm.show_versions()`
- [x] Minimal, self-contained copy-pastable example that generates the issue if possible. Please be concise with code posted. See guidelines below on how to provide a good bug report:

  - [Minimal Complete Verifiable Examples](https://stackoverflow.com/help/mcve)
  - [Craft Minimal Bug Reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

    Bug reports that follow these guidelines are easier to diagnose,
    and so are often handled much more quickly.

### Description

When calling `.to_dataset_dict()`, the datasets to load in for the CESM2-LE example notebooks

### What I Did

```python
catalog.to_dataset_dict(storage_options={'anon':True})
```

### Version information: output of `intake_esm.show_versions()`

<details>

Paste the output of `intake_esm.show_versions()` here:

```python
import intake_esm

intake_esm.show_versions()

cftime: 1.6.1
dask: 2022.8.0
fastprogress: 1.0.3
fsspec: 2022.7.1
gcsfs: None
intake: 0.6.5
intake_esm: 2021.8.17.post92
netCDF4: 1.6.0
pandas: 1.4.3
requests: 2.28.1
s3fs: 2022.7.1
xarray: 2022.6.0
zarr: 2.12.0
```

</details>

**Comment by andersy005** [comment]
Does 

```python
dsets = catalog.to_dataset_dict(xarray_open_kwargs=dict(backend_kwargs={'storage_options': {'anon': True}}))
```

work for you? With the new backend entrypoint, the storage options can be passed as part of the backend Kwargs....

**Comment by mgrover1** [comment]
That did the trick! I have a feeling this will break quite a few workflows... I wonder if we should allow the same API for storage options?

**Comment by andersy005** [comment]
> . I wonder if we should allow the same API for storage options?

I concur... i'm going to look into this, and thank you for reporting this issue.
