### ISSUE TITLE
Make a new release of intake-esm

### ISSUE THREAD

**Issue by RondeauG** [intake/intake-esm#518]
**Is your feature request related to a problem? Please describe.**
With all the recent changes to `intake-esm`, the current Release (v2021.8.17) has become very outdated compared to the `main` branch.

**Describe the solution you'd like**
A new Release (compatible with `conda/PyPi`) would be greatly appreciated.

**Comment by andersy005** [comment]
I concur... This is on my TODO list for next week (I'm heading out on vacation for a week)

**Comment by andersy005** [comment]
The newly released version `v2022.9.18` is available on `PyPI` and `conda-forge`. 

Closing this...
