### ISSUE TITLE
`aggregation_control` is documented as optional but coded as mandatory in pydantic model

### ISSUE THREAD

**Issue by huard** [intake/intake-esm#549]
### Description
The `esm-catalog-spec.md` documentation says that the `aggregation_control` field is optional https://github.com/intake/intake-esm/blob/c7cc33474564402096f3f66530828741b660f9e8/docs/source/reference/esm-catalog-spec.md?plain=1#L72 but the pydantic model defines is as mandatory https://github.com/intake/intake-esm/blob/c7cc33474564402096f3f66530828741b660f9e8/intake_esm/cat.py#L114

**Comment by mgrover1** [comment]
Thanks for pointing this out @huard - I added a PR (#551) to make sure that this is fixed.
