### ISSUE TITLE
Rewriting the Logic for the `to_datatree()` Method: Making it More Flexible

### ISSUE THREAD

**Issue by andersy005** [intake/intake-esm#562]
Recently, I had a conversation with @jbusecke about reworking the logic for the `to_datatree()` method. At present, this method utilizes `to_dataset_dict()` internally and invokes `datatree.DataTree.from_dict()`. However, as discussed with @jbusecke, we believe it would be more beneficial to make this method more adaptable by:

- disabling aggregations as the default option
- giving users the ability to specify how the datatree is populated, which could be achieved through the use of a `levels=[...]` argument.

Ccing @mgrover1 who might be interested in this 

- Towards #152

**Comment by mgrover1** [comment]
Ohh those are all great points... thanks for opening this @andersy005 . Is there a good example of how we want this to work? @jbusecke would your CMIP6 datatree workflow serve as a good use-case?

**Comment by jbusecke** [comment]
Yes this was actually the motivation for this. @TomNicholas and I have been working on https://github.com/jbusecke/easy_ipcc, and some related datatree features. 

I would like to be able to do something like:

```python
.to_datatree(levels=['source_id', 'member_id', 'experiment_id'])
```
and get a tree of this shape

```
|--source_id_a
|    |--member_id_aa
|    |     |--ex_xx
|    |     |--ex_yy
|    |--member_id_bb
|    |     |--ex_xx
|    |     |--ex_yy
|--source_id_b
     |--member_id_aa
     |     |--ex_xx
     |     |--ex_yy
     |--member_id_bb
     |     |--ex_xx
     |     |--ex_yy
```
Sorry this looks rather crappy, is there a better way to sketch out trees in a gh comment?

**Comment by mgrover1** [comment]
@jbusecke following up here - do you have any more thoughts on this? Thinking of drafting up a PR this week/have y'all test it out...

**Comment by jbusecke** [comment]
Also @TomNicholas this will be cool for easy-ipcc!
