### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by jbusecke** [intake/intake-esm#637]
Can we release a new version to incorporate #624 ?

Many thanks

**Comment by andersy005** [comment]
Done: https://github.com/intake/intake-esm/releases/tag/v2023.10.27

- [ ] pypi: https://pypi.org/project/intake-esm/2023.10.27/
- [ ] conda: not yet

**Comment by mgrover1** [comment]
@jbusecke - we cut releases last week! For both pypi and conda! Closing this! 😄

**Comment by jbusecke** [comment]
Many thanks!
