### ISSUE TITLE
Intake Take2 is about to release

### ISSUE THREAD

**Issue by martindurant** [intake/intake-esm#649]
Please consider pinning intake<2 to keep this package working, if it breaks with the new code.

**Comment by andersy005** [comment]
thank you for the heads up, @martindurant! Looking forward to trying intake v2 it out

**Comment by mgrover1** [comment]
Thanks for the heads up - and thanks @andersy005 for handling the PR/releases here.

**Comment by charles-turner-1** [comment]
We've tested upgrading to intake take2 here at ACCESS-NRI and so far haven't discovered any issues.

- All tests on intake-esm passing when upgrading to take2 ([branch](https://github.com/ACCESS-NRI/intake-esm/tree/take2)), diff:
```bash
git diff main -- ci/environment.yml
```
```diff 
diff --git a/ci/environment.yml b/ci/environment.yml
index 2f0b192..0bcfcd5 100644
--- a/ci/environment.yml
+++ b/ci/environment.yml
@@ -9,7 +9,7 @@ dependencies:
   - fsspec>=2022.11.0
   - gcsfs >=2022.11.0
   - h5netcdf>=0.8.1
-  - intake<2.0
+  - intake>=2.0
   - ipython
   - matplotlib
   - netcdf4>=1.5.5
@@ -26,7 +26,7 @@ dependencies:
   - pytest-mock
   - s3fs >=2022.11.0
   - scipy
-  - xarray>=2022.06
+  - xarray>=2022.06, !=2024.10
   - xarray-datatree
   - zarr>=2.12
   # - pytest-icdiff
```
    NB. `xarray 2024.10` seems to be causing some issues - it looks like they did a lot of work related to datatree in this version & potentially renamed some modules - I'm looking into it further now.
- All of our tests are passing on both `intake<2.0` and `intake >=2.0`: see https://github.com/ACCESS-NRI/access-nri-intake-catalog/pull/233 and [tox file](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/main/tox.ini).

We haven't run any E2E tests yet, so I'm not 100% sure that nothing breaks (in our use case), but as of right now I'm pretty confident that upgrading to intake take2 is unlikely to cause any issues for intake-esm.

**Comment by andersy005** [comment]
thank you for looking into this, @charles-turner-1! when you get a chance, do you mind opening a PR with this change?
