### ISSUE TITLE
Extend search method to filter rows in collection by wildcard

### ISSUE THREAD

**Issue by andersy005** [intake/intake-esm#92]
It would be nice to extend our search method to allow passing in regular expressions. 

The current search method works for **exact matches** only. 

For example, the following works out of the box:

```python
col.search(variable=['TEMP'], case=['b.e11.BRCP85C5CNBDRD.f09_g16.103', 'b.e11.BRCP85C5CNBDRD.f09_g16.102'])
```

With regular expression, you could search for something like:

```python
col.search(variable=['TEMP'], case='b.e11.B20TRC5CNBDRD.f09_g16.10*')

```

Ccing

@matt-long, @kmpaul, @jukent

**Comment by andersy005** [comment]
I needed this functionality so badly right -:). So, I just implemented a quick prototype in #93, and it seems to be working fine. Will close this issue once #93 is merged.

**Comment by matt-long** [comment]
This is a good feature, but we should be clear on the syntax: is it regex or glob pattern? I think you are showing a glob pattern.

**Comment by andersy005** [comment]
> This is a good feature, but we should be clear on the syntax: is it regex or glob pattern? I think you are showing a glob pattern.

I closed this issue too early, and found some problems including the `glob` vs `regex` issues ( I am trying to address them right now)

**Comment by andersy005** [comment]
Just listing a few instances where `regex`  with `globbing`:

Special Character | Meaning in Globs | Meaning in Regex
------------------ | --------------- | --------------------------
`*`                           | zero or more characters | zero or more of the character it follows
? | single occurrence of any character | zero or one of the character it follows but not more than 1
. | literal "." character | any single character

**Comment by andersy005** [comment]
We all see need to be able to turn the regex off when exact matches are wanted.

I found out that this query
```python
col.search(variable='SHF')
``` 

ends up returning both `SHF_QSW`, and `SHF` variables, even though I wanted just `SHF` in this case. 

@matt-long, what would be an ideal default, having `regex` parameter turned off or on?

```python
def search(self, case_sensitive=False, regex=True, **query):
        """ Search for entries in the collection catalog
        Parameters
        ----------
        
        case: bool, default True
              If True, case sensitive.

        regex: bool, default True
            If True, assumes the query is a regular expression.
            If False, treats the query as a literal string.
        
        query: (dict, optional) Keywords passed to get_subset()

        Returns
        -------
        A catalog entry on the local system
        """
```

**Comment by matt-long** [comment]
Globus CLI has something like this:
```
     Filter patterns must start with =, ~, !, or !~
        If none of these are given, = will be used
        = does exact matching
        ~ does regex matching, supporting globs (*)
        ! does inverse = matching
        !~ does inverse ~ matching
```

We could detect strings that start with `~` and trigger `regex` or `glob` matching behavior therein. The documentation above is a little confusing, omitting a distinction between regex and glob.
